name: CMD-RNASEQFUS-STARFUS 
channels:
    - bioconda
    - conda-forge
    - defaults

dependencies:
    #- bioconda::fusion-inspector=2.2.1
    #- bioconda::star-fusion=1.7.0
    #- perl
    #- bioconda::bioconductor-genomicfeatures
    #- bioconda::bioconductor-org.hs.eg.db
    #- bioconda::bioconductor-biomart 
    #- bioconda::bioconductor-polyester=1.22.0
    #- bioconda::bioconductor-biostrings=2.54.0
    #- conda-forge::r-foreach=1.4.7
    #- conda-forge::r-doparallel=1.0.15
     - bioconda::fusioncatcher=1.20



